name: Sample CI

on:
  push:
    branches:
      - '**' # Run on push to all branches
  pull_request:
    branches:
      - '**' # Run on pull request to all branches
  paths-ignore:
    - 'README.md'
jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello Github!"

  test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./kotlin/url-shortener/gradlew test

      - name: Upload test results
        if: always() # Upload even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test # Adjust path if your build setup is different